debug: True
log:
  level: DEBUG

entryPoints:
  web-entry:
    address: :80
  web-entry-secure:
    address: :443


api:
  insecure: true
  dashboard: true
  debug: true


providers:
  docker:
    exposedByDefault: false
    endpoint: "tcp://127.0.0.1:2375"
    swarmMode: true
